name: test
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        extra: ["dev", "dev,sqlite", "dev,duckdb"]  # ← Changed this
    env:
      PG_URL: postgresql://postgres:secret@localhost/postgres
      MY_URL: mysql://root:secret@localhost:3306/vectordb
    services:
      postgres:
        image: ankane/pgvector:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: secret
        options: --health-cmd="pg_isready -U postgres" --health-interval=5s --health-retries=5
      mysql:
        image: mysql:8.0
        ports: ["3306:3306"]
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: vectordb
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -psecret" --health-interval=5s --health-retries=12
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          python -m pip install ".[${{ matrix.extra }}]"  # ← Changed this
      - run: pytest -q
